In [20]:
import numpy as np

In [25]:
a = np.array([[1,2,3] ,[4,5,6]])
a.shape

int32


In [26]:
a.dtype

dtype('int32')

In [28]:
a = np.arange(60)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [34]:
a = a.reshape(3,4,5)
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [35]:
print(a[...,3])

[[ 3  8 13 18]
 [23 28 33 38]
 [43 48 53 58]]


In [36]:
print(a[1,...,3])

[23 28 33 38]


In [38]:
print(a[2,...,3])

[43 48 53 58]


In [39]:
print(a[... ,2])

[[ 2  7 12 17]
 [22 27 32 37]
 [42 47 52 57]]


In [41]:
print(a[: , : , 2])

[[ 2  7 12 17]
 [22 27 32 37]
 [42 47 52 57]]


In [42]:
print(a[2,... , 2])

[42 47 52 57]


In [45]:
print(a[ 0, :: 2 , :: 2])

[[ 0  2  4]
 [10 12 14]]


In [46]:
print(a[0 , :: 1 , :: 2])

[[ 0  2  4]
 [ 5  7  9]
 [10 12 14]
 [15 17 19]]


In [47]:
# minimum dimensions 
a = np.array([1,2,3,4,5] , ndmin = 2)
print(a)

[[1 2 3 4 5]]


In [48]:
a = np.array([1,2,3,4,5]  , ndmin = 1)
print(a)

[1 2 3 4 5]


In [50]:
# dtype

a = np.array([1,2,3,4,5] , dtype = complex )
print(a)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]


In [54]:
# using array scalar type 

dt = np.dtype( np.int32)
print(dt)


int32


In [55]:
# int8  , int16, int32 , int64 can be replaced with 'i1' , 'i2' , 'i3' , 'i4' respectively 
dt = np.dtype('i2')
print(dt)

int16


In [59]:
# using endian notation 

dt = np.dtype('>i4')
print(dt)

>i4


In [61]:
# creating a structured data type 

dt  = np.dtype([('age' , np.int32)])
print(dt)

[('age', '<i4')]


In [63]:
# aplying it to ndarrya object 

a = np.array([(10,) , (20, ) , (30,)] , dtype = dt)
print(a)

[(10,) (20,) (30,)]


In [65]:
# using file name to access elements 

dt = np.dtype([('age' , np.int64)])
a = np.array([(10,) , (20,) , (30,)] , dtype = dt)
print(a['age'])

[10 20 30]


In [67]:
# using string , int , float data types to assigns individual file names

name = np.dtype([('name' , 'S20') , ('age' , 'i1') , ('marks' , 'f4')])
print(name)

[('name', 'S20'), ('age', 'i1'), ('marks', '<f4')]


In [70]:
# creating an array of the above data types 

name2 = np.array([('abc' , 12,14) , ('name' , 12 , 45.6) ], dtype = name)
print(name2)

[(b'abc', 12, 14. ) (b'name', 12, 45.6)]


In [75]:
# accessing elements using file name 
print(name2['name'])
print(name2['age'])
print(name2['marks'])

[b'abc' b'name']
[12 12]
[14.  45.6]


In [76]:
# using ndarray.shape ( returning the tuple size )

print(name2.shape)

(2,)


In [83]:
# resizes the array 

a = np.array([[1,2,3] , [4,5,6]])
a.shape= (3,2)
print(a)
print()
print(a.shape)


[[1 2]
 [3 4]
 [5 6]]

(3, 2)


In [97]:
# reshape to resize the array 

a = np.array([[1,2,3] , [4,5,6]])
b = a.reshape(3,2)
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [99]:
# array dimensions 

a = np.arange(24)
print(a)
print(a.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1


In [101]:
a = a.reshape(3,2 , 4)
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]


In [108]:
temp =name2.reshape(2,1)
print(temp)

[[(b'abc', 12, 14. )]
 [(b'name', 12, 45.6)]]


In [114]:
# itemsize : length of the each element of the array 
# itemsize of int8 is  (1 byte )
# itemsize of int32 is ( 4 byte)
# itemsize of int64 is ( 8 byte )
# itemsize of float32 is ( 4 byte )

print(a.itemsize)
print(a.dtype)
print(np.array([(1,2,3)] , dtype = 'int64').itemsize)
print(np.array([(1,2,3) , (4,5,6)] , dtype = 'float32').itemsize)

4
int32
8
4


In [115]:
# flags 

print(a.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False



In [118]:
# numpy.empty 
# numpy.empty(shape, dtype=float, order='C') 

b = np.empty([3,2] , dtype = 'float32' , order = 'C')
print(b.dtype)
print(b.shape)

float32
(3, 2)


In [119]:
print(b)

[[1.e-45 3.e-45]
 [4.e-45 6.e-45]
 [7.e-45 8.e-45]]


In [120]:
b = np.empty([3,2] , dtype = 'int32')
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [121]:
# specifying an array filled with zeros 
# numpy.zeros(shape, dtype=float, order='C') 

c = np.zeros([2,3] , dtype = 'int32' , order = 'F')
print(c)

[[0 0 0]
 [0 0 0]]


In [128]:
c = np.zeros([2,3] , dtype = 'int32' , order = 'C')
print(c)
print(c.ndim)

[[0 0 0]
 [0 0 0]]
2


In [127]:
x = np.zeros((2,2) , dtype = [('x' , 'i4') , ('y' , 'i2')] , order= 'C')
print(x)
print(x.shape)
print(x.ndim)

[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]
(2, 2)
2


In [129]:
# numpy ones  ( specifying all the array elements to one )
# numpy.ones(shape, dtype=None, order='C') 

a = np.ones((2,3) , dtype = np.float32 , order = 'C') 
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [130]:
print(np.ones([3,4] , dtype = np.int32 , order = 'F'))

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [132]:
# nupmy asarray 
# numpy.asarray(a, dtype=None, order=None) 
# a = input data from lists ,tuples etc 
# same as nupmy array but with fewer parameters 

x = [1,2,3]
print(np.asarray(x))
print(np.asarray(x).shape)

[1 2 3]
(3,)


In [135]:
a = np.asarray(x ,dtype = np.float32)
print(a)
a =a.reshape(3,1)
print()
print(a)


[1. 2. 3.]

[[1.]
 [2.]
 [3.]]


In [138]:
x = [(1,2,3) , (4,5,6)]
print(np.asarray(x , dtype = np.int32))
b = np.array(x , dtype= np.int32)
b = b.reshape(3,2)
print()
print(b)

[[1 2 3]
 [4 5 6]]

[[1 2]
 [3 4]
 [5 6]]


In [158]:
# numpy buffer, interprets buffer as a 1-d array 
# numpy.frombuffer(buffer, dtype=float, count=-1, offset=0) 

# buffer = an object that exposes buffer interface 
# count = The number of items to read, default -1 means all data 
# offset = starting position to read from 

s = 'Atharva Pingale'
d = np.frombuffer(s.encode(), dtype = 'S1')
print(d)

[b'A' b't' b'h' b'a' b'r' b'v' b'a' b' ' b'P' b'i' b'n' b'g' b'a' b'l'
 b'e']


In [162]:
# numpy from iter, creates an ndarray around an iterable object 
# numpy.fromiter(iterable, dtype, count=-1) 


# iterable = any iterable object 
# dtype = data type 
# count = number of items to be read from iterator , -1 if remaining to read all items 

list = range(10)
print(list)
it = iter(list)
print(it)
c = np.fromiter(it , dtype= np.int32)
print(c)

range(0, 10)
[0 1 2 3 4 5 6 7 8 9]


In [167]:
# numpy arange 
# numpy.arange(start , stop , step , dtype )

# step = spacing by defalt is 1 

x = np.arange(5)
print(x)
print(np.arange(6 , dtype = np.float32))
print(np.arange(10 , step = 3 , dtype = np.float32))

[0 1 2 3 4]
[0. 1. 2. 3. 4. 5.]
[0. 3. 6. 9.]
