In [1]:
import numpy as np


In [2]:
# numpy broadcasting 

x = np.array([1,2,3,4,5])
print(x)
y =np.array([10,20,30,40,50])
print(y)
z = x*y
print(z)

[1 2 3 4 5]
[10 20 30 40 50]
[ 10  40  90 160 250]


In [6]:
# addition of numpy arrays 

x = np.array([[0,1,2],
               [3,4,5],
               [6,7,8],
               [9,10,11]])
y = np.array([1,2,3])
z = x + y
print("Addition : \n")
print(z)

Addition : 

[[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]
 [10 12 14]]


In [12]:
# iterating over an array using nditer

a = np.arange(0,60,5)
a = a.reshape(3,4)
print(a)
print()
# iterating over the array
for x in np.nditer(a):
    print(x , end=" ")

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]

0 5 10 15 20 25 30 35 40 45 50 55 

In [14]:
a = np.arange(0,60,5)
a = a.reshape(3,4)
print(a)
print("\nTranspose of the array : \n")
b = a.T
print(b)

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]

Transpose of the array : 

[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]


In [15]:
c = b.copy(order= 'C')
print("In C style order : \n")
print(c)


In C style order : 

[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]


In [16]:
d = b.copy(order  ='C')
print("In F style order : \n")
print(d)

In F style order : 

[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]


In [ ]:
# NOTE - iterating through a F style array is faster than iterating through a C style array 

In [18]:
# modifying all the array values 

a =np.arange(0,60,5)
print(a)
for x in np.nditer(a , op_flags =['readwrite']): 
    x[...] = x/2

print()
print(a)

[ 0  5 10 15 20 25 30 35 40 45 50 55]

[ 0  2  5  7 10 12 15 17 20 22 25 27]


In [21]:
a = np.arange(0,60,5)
a= a.reshape(3,4)

# using flags
for x in np.nditer(a , flags=['external_loop'] , order = 'F'): 
    print(x)

# external_loop = instead of accessing the element as 0 dimension array, accesses the array as one dimensional array 
# c_index = c_order index can be tracked 
# f_index = f_order index can be tracked 
# multi-index = types of index with one per iteration can be tracked 

[ 0 20 40]
[ 5 25 45]
[10 30 50]
[15 35 55]


In [39]:
# combining a list of arrays in nditer 

a = np.arange(0,60,5)
a =a.reshape(3,4)
print(a)
b = np.array([1,2,3,4])
# The array should exactly be of the same size as the number of columns in the aboce ( main array ).
print()
for x,y in np.nditer([a,b]): 
    print("%d:%d"  %(x,y) , end=" ")

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]

0:1 5:2 10:3 15:4 20:1 25:2 30:3 35:4 40:1 45:2 50:3 55:4 

In [40]:
# numpy reshape 
# numpy.reshape(arr, newshape, order') 

In [49]:
# numpy array flat 
# flattens the array to 1 dimensional 

a = np.arange(0,60,5).reshape(3,4)
print(a)
print(a.flat[5])
# flattens the array to 1D array and extracts 5th element from it

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
25


In [56]:
# numpy array flatten
# This function returns a copy of an array collapsed into one dimension. The function takes the following parameters. 
# ndarray.flatten(order) 

a = np.arange(0,60,5).reshape(3,4)
print(a)
print(a.flatten(order = 'C'))
# flattens teh array to C style 

print(a.flatten(order = 'F'))
# flattens the array to F style 

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
[ 0  5 10 15 20 25 30 35 40 45 50 55]
[ 0 20 40  5 25 45 10 30 50 15 35 55]


In [59]:
# numpy ravel 
# returns a flat one dimensional array 
a = np.arange(0,60,5).reshape(3,4)
print(a)

a = np.ravel(a , order = 'C')
print(a)
# completely flattens the array to one dimensional array 

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
[ 0  5 10 15 20 25 30 35 40 45 50 55]


In [62]:
# numpy transpose 

a = np.arange(0,60,5).reshape(3,4)
print(a)
# using transpose 

a = np.transpose(a)
# by default the axes parameter reverses the axes 
print()
print(a)


[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]

[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]


In [64]:
# numpy T 
# used for transpose 

a = np.arange(0,60,5).reshape(3,4)
print(a)
print()
print(a.T)

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]

[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]


In [68]:
# numpy swap axes 
# This function interchanges the two axes of an array. 
# For NumPy versions after 1.10, a view of the swapped array is returned. 
# The function takes the following parameters. 
# numpy.swapaxes(arr, axis1, axis2) 

a = np.arange(0,40,5).reshape(2,2,2)
print(a)
print("\nAfter swapping : \n")
a = np.swapaxes(a , 2,0)
print(a)

[[[ 0  5]
  [10 15]]

 [[20 25]
  [30 35]]]
After swapping : 
[[[ 0 20]
  [10 30]]

 [[ 5 25]
  [15 35]]]
