In [2]:
import numpy as np

In [4]:
# numpy : linspace 
# This function is similar to arange() function. In this function, instead of step size, 
# the number of evenly spaced values between the interval is specified. 
# The usage of this function is as follows: 
# numpy.linspace(start, stop, num, endpoint, retstep, dtype) 

# start = the starting value 
# stop = the stop value 
# num = the number of evenly spaces samples. default is 50 
# endpoint = true by default ( if including stop as well ) , false ( excludes stop )
# retstep = true , returns samples and step between the consecutive numbers 
# dtype = data type 

a = np.linspace(10 , 20 , 5)
print(a)


[10.  12.5 15.  17.5 20. ]


In [6]:
x = np.linspace(10 , 20 , 5 , endpoint = False)
print(x)

[10. 12. 14. 16. 18.]


In [8]:
x = np.linspace(10 , 20 , 5 , retstep = True)
print(x)

(array([10. , 12.5, 15. , 17.5, 20. ]), 2.5)


In [10]:
# numpy logspace 
# returns nparray object that contains the numbers that are evenly spaced on a log scale 
# numpy.logscale(start, stop, num, endpoint, base, dtype) 

# start = start of the sequence 
# stop = stop of the sequence 
# num = number of evely spaced values. 50 by default 
# endpoint = TRUE by defaault ( includes stop ). false ( excludes stop )
# base = base of the log 
# dtype = data type 

a = np.logspace(10 , 20 , num = 5 , base = 2)
print(a)

[1.02400000e+03 5.79261875e+03 3.27680000e+04 1.85363800e+05
 1.04857600e+06]


In [14]:
# numpy slice 
# slices the array 

a = np.arange(10)
b = slice(2,7,2)
print(a[b])

[2 4 6]


In [19]:
a = np.arange(20)
print(a[2:7:2])
print(a[5])
print(a[2:])
print(a[: 13])
print(a[2: 10])

[2 4 6]
5
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
[2 3 4 5 6 7 8 9]


In [21]:
a = np.array([(1,2,3) , (4,5,6) , (7,8,9)])
print(a)
print()
print(a[1:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[4 5 6]
 [7 8 9]]


In [25]:
print(a[... , 1])# items in teh 2nd col

[2 5 8]


In [26]:
print(a[... ,2])
# items in the 3rd col

[3 6 9]


In [27]:
print(a[1,...])
# items in the 2nd row 

[4 5 6]


In [48]:
# advanced indexing 
a = np.array([[1,2] ,[3,4] , [5,6]])
print(a)
print(a.ndim)
print()
 # print(a[[1,0] , [0,1] , [1,1]])
b = a[[0,1,2] , [0,1,0]]
print()
print(a[[0,1,2,0,1] , [0,1,0,1,0]])
print()
print(b)


[[1 2]
 [3 4]
 [5 6]]
2


[1 4 5 2 3]

[1 4 5]


In [52]:
x = np.array([[0,1,2] , [3,4,5] , [6,7,8] , [9,10,11]])
print(x)
rows = np.array([[0,0] , [3,3]])
cols = np.array([[0,2], [1,2]])
b = x[rows  , cols]
print()
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[[ 0  2]
 [10 11]]


In [54]:
# boolean array indexing 

x = np.array([[0,1,2] , [3,4,5] , [6,7,8]])
print(x[x> 5])
# prints all the elements greater than 5

[6 7 8]


In [69]:
# NaN numbers 

x= np.array([[np.nan , 1] , [2 , np.nan]])
print(x)

#ommiting the nan number s
print()
print(x[~np.isnan(x)])
print(x)
print(x.dtype)

[[nan  1.]
 [ 2. nan]]

[1. 2.]
[[nan  1.]
 [ 2. nan]]
float64


In [73]:
# complex numbers 

x = np.array([[1 , 2+6j] , [3+7j , 5]])
print(x)
print()

# printing complex numbers
print(x[~np.iscomplex(x)])

# ommiting the complex numbers 
print()
print(x[np.iscomplex(x)])

[[1.+0.j 2.+6.j]
 [3.+7.j 5.+0.j]]

[1.+0.j 5.+0.j]

[2.+6.j 3.+7.j]
